apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xvms
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-xvms@sha256:00e1733dee86b55e0a5422e7d434a35d0fa73dd6b9c5cff8cc224b3389050ddd
        name: my-nodejs
        resources: {}
status: {}
